export const PROFILE_CAMS = [
	{
		id: 1,
		displayName: "Jane Adams",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image3.png",
	},
	{
		id: 2,
		displayName: "Mia Vale",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image1.png",
	},
	{
		id: 3,
		displayName: "Violet Pulse",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image2.png",
	},
	{
		id: 4,
		displayName: "Claire Hill",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image3.png",
	},
	{
		id: 5,
		displayName: "Thelma Smith",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image2.png",
	},
	{
		id: 6,
		displayName: "Divine Adams",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image1.png",
	},
	{
		id: 7,
		displayName: "Jane Adams",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image2.png",
	},
	{
		id: 8,
		displayName: "Jane Adams",
		age: "23",
		cost: "$23",
		time: "1min",
		src: "/post/post-image3.png",
	},
];
